### PR TITLE
Rename Readonly to IsReadonly in order to allow BC

### LINKED ISSUE #6: Not compatible with PHP 8.1
`readonly` is a token in php 8.1 so having attributes with same name cause parse error there.

WDYT about renaming the attribute to `IsReadonly` and tagging v0.2?

### PR DESCRIPTION
**Pull request by simPod**
Resolves #6

### CODE REVIEW

**Review by icanhazstring — CHANGES_REQUESTED** [review]
Thanks! Can you update the `README.md` as well?

**Comment by simPod** [comment]
ah right, done

**Review by icanhazstring — APPROVED** [review]
Thanks for the quick update.

**Comment by icanhazstring** [comment]
Tagged with 0.2.0

**Pull request merged**
